### ISSUE TITLE
Rainfall Flooded Road Notifications

### ISSUE THREAD

**Issue by yenyang** [Katalyst6/CSL.TransitAddonMod#14]
Hi I am the Author of [Rainfall](http://steamcommunity.com/sharedfiles/filedetails/?id=698395457) and I would like to change the tolerance for flooding notifications of roads. Unfortunately its located at RoadbaseAI.SimulationStep() and this mod is already overriding that function. 
If you could change 

```
if (num6 > vector.y + 1f) {
    flag = true;
    data.m_flags |= NetSegment.Flags.Flooded;
    problem = Notification.AddProblems(problem, Notification.Problem.Flood | Notification.Problem.MajorProblem);
} else {
    data.m_flags &= ~NetSegment.Flags.Flooded;
    if (num6 > vector.y) {
            flag = true;
            problem = Notification.AddProblems(problem, Notification.Problem.Flood);
    }
}
```

 to 

```
if (num6 > vector.y + 1f) {
    flag = true;
    data.m_flags |= NetSegment.Flags.Flooded;
    problem = Notification.AddProblems(problem, Notification.Problem.Flood | Notification.Problem.MajorProblem);
} else {
    data.m_flags &= ~NetSegment.Flags.Flooded;
    if (num6 > vector.y+0.5f) {
            flag = true;
            problem = Notification.AddProblems(problem, Notification.Problem.Flood);
    }
}
```

That would be a great start. I'm not sure If It will be perfect, but it's alot better than the current method.
Edit it's located at this file CSL.TransitAddonMod/TLM/Custom/AI/CustomRoadAI.cs

**Comment by MattSturgeon** [comment]
@yenyang, if you know the code changes needed, why not send a pull request? :smile:

**Comment by Katalyst6** [comment]
@yenyang Thanks for sharing your concerns with us! Unfortunately, neither T++ V2 or NExt is currently altering that piece of code you are talking about. 
That being said, I know the Traffic Manager President is altering it, as well as the long awaited Transit Addon Mod (TAM). 
If you want to speed up things a little bit, i strongly suggest that you write a message directly to LinuxFan so he will probably be able to do something about it for TM until proven otherwise.

Cheers!

**Comment by yenyang** [comment]
@MattSturgeon Sorry, this stuff is still pretty new to me.
@Katalyst6 Ok Thank you.
